[bridge]
monitor_interval_sec = 60 # (int) set to -1 or lower for "oneshot" mode

[webodm]
url = "https://webodm.rettungsrobotik.de"
project = "CREXDATA Trials"
asset = 'dsm.tif'

[kafka]
#url = "localhost:9092"
url = "server.crexdata.eu:9192"
topic = "UPB-CREXDATA-RealtimeDEM-Stream"
key = "dsm.tif"

# Enable this block if Kafka cluster requires authentication
#[kafka.auth]
#cert_dir = "config/certs" # absolute path, or relative to current working directory
#ca = "kafka_ca.crt"
#client_crt = "kafka_client.crt"
#client_key = "kafka_client.key"
